export const countries = [
  { "label": "AFGANISTÁN", "code": "93" },
  { "label": "ALBANIA", "code": "355" },
  { "label": "ALEMANIA", "code": "49" },
  { "label": "ANDORRA", "code": "376" },
  { "label": "ANGOLA", "code": "244" },
  { "label": "ARABIA SAUDITA", "code": "966" },
  { "label": "ARGELIA", "code": "213" },
  { "label": "ARGENTINA", "code": "54" },
  { "label": "ARMENIA", "code": "374" },
  { "label": "AUSTRALIA", "code": "61" },
  { "label": "AUSTRIA", "code": "43" },
  { "label": "AZERBAIYÁN", "code": "994" },
  { "label": "BAHAMAS", "code": "1-242" },
  { "label": "BANGLADÉS", "code": "880" },
  { "label": "BARBADOS", "code": "1-246" },
  { "label": "BARÉIN", "code": "973" },
  { "label": "BÉLGICA", "code": "32" },
  { "label": "BELICE", "code": "501" },
  { "label": "BENÍN", "code": "229" },
  { "label": "BIELORRUSIA", "code": "375" },
  { "label": "BOLIVIA", "code": "591" },
  { "label": "BOSNIA Y HERZEGOVINA", "code": "387" },
  { "label": "BOTSUANA", "code": "267" },
  { "label": "BRASIL", "code": "55" },
  { "label": "BRUNÉI", "code": "673" },
  { "label": "BULGARIA", "code": "359" },
  { "label": "BURKINA FASO", "code": "226" },
  { "label": "BURUNDI", "code": "257" },
  { "label": "BUTÁN", "code": "975" },
  { "label": "CABO VERDE", "code": "238" },
  { "label": "CAMBOYA", "code": "855" },
  { "label": "CAMERÚN", "code": "237" },
  { "label": "CANADÁ", "code": "1" },
  { "label": "CATAR", "code": "974" },
  { "label": "CHAD", "code": "235" },
  { "label": "CHILE", "code": "56" },
  { "label": "CHINA", "code": "86" },
  { "label": "CHIPRE", "code": "357" },
  { "label": "COLOMBIA", "code": "57" },
  { "label": "COMORAS", "code": "269" },
  { "label": "COREA DEL NORTE", "code": "850" },
  { "label": "COREA DEL SUR", "code": "82" },
  { "label": "COSTA DE MARFIL", "code": "225" },
  { "label": "COSTA RICA", "code": "506" },
  { "label": "CROACIA", "code": "385" },
  { "label": "CUBA", "code": "53" },
  { "label": "DINAMARCA", "code": "45" },
  { "label": "DOMINICA", "code": "1-767" },
  { "label": "ECUADOR", "code": "593" },
  { "label": "EGIPTO", "code": "20" },
  { "label": "EL SALVADOR", "code": "503" },
  { "label": "EMIRATOS ÁRABES UNIDOS", "code": "971" },
  { "label": "ERITREA", "code": "291" },
  { "label": "ESLOVAQUIA", "code": "421" },
  { "label": "ESLOVENIA", "code": "386" },
  { "label": "ESPAÑA", "code": "34" },
  { "label": "ESTADOS UNIDOS", "code": "1" },
  { "label": "ESTONIA", "code": "372" },
  { "label": "ETIOPÍA", "code": "251" },
  { "label": "FILIPINAS", "code": "63" },
  { "label": "FINLANDIA", "code": "358" },
  { "label": "FIYI", "code": "679" },
  { "label": "FRANCIA", "code": "33" },
  { "label": "GABÓN", "code": "241" },
  { "label": "GAMBIA", "code": "220" },
  { "label": "GEORGIA", "code": "995" },
  { "label": "GHANA", "code": "233" },
  { "label": "GRANADA", "code": "1-473" },
  { "label": "GRECIA", "code": "30" },
  { "label": "GUATEMALA", "code": "502" },
  { "label": "GUINEA", "code": "224" },
  { "label": "GUINEA-BISÁU", "code": "245" },
  { "label": "GUINEA ECUATORIAL", "code": "240" },
  { "label": "GUYANA", "code": "592" },
  { "label": "HAITÍ", "code": "509" },
  { "label": "HONDURAS", "code": "504" },
  { "label": "HUNGRÍA", "code": "36" },
  { "label": "INDIA", "code": "91" },
  { "label": "INDONESIA", "code": "62" },
  { "label": "IRÁN", "code": "98" },
  { "label": "IRAK", "code": "964" },
  { "label": "IRLANDA", "code": "353" },
  { "label": "ISLANDIA", "code": "354" },
  { "label": "ISLAS MARSHALL", "code": "692" },
  { "label": "ISLAS SALOMÓN", "code": "677" },
  { "label": "ISRAEL", "code": "972" },
  { "label": "ITALIA", "code": "39" },
  { "label": "JAMAICA", "code": "1-876" },
  { "label": "JAPÓN", "code": "81" },
  { "label": "JORDANIA", "code": "962" },
  { "label": "KAZAJISTÁN", "code": "7" },
  { "label": "KENIA", "code": "254" },
  { "label": "KIRGUISTÁN", "code": "996" },
  { "label": "KIRIBATI", "code": "686" },
  { "label": "KUWAIT", "code": "965" },
  { "label": "LAOS", "code": "856" },
  { "label": "LESOTO", "code": "266" },
  { "label": "LETONIA", "code": "371" },
  { "label": "LÍBANO", "code": "961" },
  { "label": "LIBERIA", "code": "231" },
  { "label": "LIBIA", "code": "218" },
  { "label": "LIECHTENSTEIN", "code": "423" },
  { "label": "LITUANIA", "code": "370" },
  { "label": "LUXEMBURGO", "code": "352" },
  { "label": "MACEDONIA DEL NORTE", "code": "389" },
  { "label": "MADAGASCAR", "code": "261" },
  { "label": "MALASIA", "code": "60" },
  { "label": "MALAUI", "code": "265" },
  { "label": "MALDIVAS", "code": "960" },
  { "label": "MALI", "code": "223" },
  { "label": "MALTA", "code": "356" },
  { "label": "MARRUECOS", "code": "212" },
  { "label": "MAURICIO", "code": "230" },
  { "label": "MAURITANIA", "code": "222" },
  { "label": "MÉXICO", "code": "52" },
  { "label": "MICRONESIA", "code": "691" },
  { "label": "MOLDAVIA", "code": "373" },
  { "label": "MÓNACO", "code": "377" },
  { "label": "MONGOLIA", "code": "976" },
  { "label": "MONTENEGRO", "code": "382" },
  { "label": "MOZAMBIQUE", "code": "258" },
  { "label": "MYANMAR", "code": "95" },
  { "label": "NAMIBIA", "code": "264" },
  { "label": "NAURU", "code": "674" },
  { "label": "NEPAL", "code": "977" },
  { "label": "NICARAGUA", "code": "505" },
  { "label": "NÍGER", "code": "227" },
  { "label": "NIGERIA", "code": "234" },
  { "label": "NORUEGA", "code": "47" },
  { "label": "NUEVA ZELANDA", "code": "64" },
  { "label": "OMÁN", "code": "968" },
  { "label": "PAÍSES BAJOS", "code": "31" },
  { "label": "PAKISTÁN", "code": "92" },
  { "label": "PALAOS", "code": "680" },
  { "label": "PANAMÁ", "code": "507" },
  { "label": "PAPÚA NUEVA GUINEA", "code": "675" },
  { "label": "PARAGUAY", "code": "595" },
  { "label": "PERÚ", "code": "51" },
  { "label": "POLONIA", "code": "48" },
  { "label": "PORTUGAL", "code": "351" },
  { "label": "REINO UNIDO", "code": "44" },
  { "label": "REPÚBLICA CENTROAFRICANA", "code": "236" },
  { "label": "REPÚBLICA CHECA", "code": "420" },
  { "label": "REPÚBLICA DEL CONGO", "code": "242" },
  { "label": "REPÚBLICA DEMOCRÁTICA DEL CONGO", "code": "243" },
  { "label": "REPÚBLICA DOMINICANA", "code": "1-809" },
  { "label": "RUANDA", "code": "250" },
  { "label": "RUMANIA", "code": "40" },
  { "label": "RUSIA", "code": "7" },
  { "label": "SAMOA", "code": "685" },
  { "label": "SAN CRISTÓBAL Y NIEVES", "code": "1-869" },
  { "label": "SAN MARINO", "code": "378" },
  { "label": "SAN VICENTE Y LAS GRANADINAS", "code": "1-784" },
  { "label": "SANTA LUCÍA", "code": "1-758" },
  { "label": "SANTO TOMÉ Y PRÍNCIPE", "code": "239" },
  { "label": "SENEGAL", "code": "221" },
  { "label": "SERBIA", "code": "381" },
  { "label": "SEYCHELLES", "code": "248" },
  { "label": "SIERRA LEONA", "code": "232" },
  { "label": "SINGAPUR", "code": "65" },
  { "label": "SIRIA", "code": "963" },
  { "label": "SOMALIA", "code": "252" },
  { "label": "SRI LANKA", "code": "94" },
  { "label": "SUAZILANDIA", "code": "268" },
  { "label": "SUDÁFRICA", "code": "27" },
  { "label": "SUDÁN", "code": "249" },
  { "label": "SUDÁN DEL SUR", "code": "211" },
  { "label": "SUECIA", "code": "46" },
  { "label": "SUIZA", "code": "41" },
  { "label": "SURINAM", "code": "597" },
  { "label": "TAILANDIA", "code": "66" },
  { "label": "TANZANIA", "code": "255" },
  { "label": "TAYIKISTÁN", "code": "992" },
  { "label": "TIMOR ORIENTAL", "code": "670" },
  { "label": "TOGO", "code": "228" },
  { "label": "TONGA", "code": "676" },
  { "label": "TRINIDAD Y TOBAGO", "code": "1-868" },
  { "label": "TÚNEZ", "code": "216" },
  { "label": "TURKMENISTÁN", "code": "993" },
  { "label": "TURQUÍA", "code": "90" },
  { "label": "TUVALU", "code": "688" },
  { "label": "UCRANIA", "code": "380" },
  { "label": "UGANDA", "code": "256" },
  { "label": "URUGUAY", "code": "598" },
  { "label": "UZBEKISTÁN", "code": "998" },
  { "label": "VANUATU", "code": "678" },
  { "label": "VATICANO", "code": "379" },
  { "label": "VENEZUELA", "code": "58" },
  { "label": "VIETNAM", "code": "84" },
  { "label": "YEMEN", "code": "967" },
  { "label": "YIBUTI", "code": "253" },
  { "label": "ZAMBIA", "code": "260" },
  { "label": "ZIMBABUE", "code": "263" }
];
